name: Banking CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake lcov
        
    - name: Configure and build
      run: |
        cd banking  
        mkdir build
        cd build
        cmake .. -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON
        make
        
    - name: Run tests
      run: |
        cd banking/build
        ctest --output-on-failure
        
   - name: Generate coverage
  run: |
    cd banking/build
    lcov --ignore-errors mismatch --ignore-errors gcov --capture --directory . -o coverage.info || lcov --ignore-errors gcov --capture --directory . -o coverage.info
    lcov --extract coverage.info "*/banking/*.h" "*/banking/*.cpp" -o filtered_coverage.info
          
    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: banking/build/coverage.info
